### ISSUE TITLE
Integration - 🔌

### ISSUE THREAD

**Issue by dandv** [dannyfritz/commit-message-emoji#41]
A more specific type of feature. [Used](https://raw.githubusercontent.com/apollographql/apollo-server/master/.github/PULL_REQUEST_TEMPLATE.md) by the apollographql project.

Or - could it suggest "dependencies" better than the cards index (metadata)? The example below from the README is a bit confusing to me:

![image](https://user-images.githubusercontent.com/33569/82129882-080c0b00-977b-11ea-8a32-66bd38491f84.png)

**Comment by dannyfritz** [comment]
I see dependency lists as metadata generally. I don't want to change it to a plug because dependencies is a much narrower view of metadata. I get you want a better emoji for dependencies/integrations, but there are many other metadata changes that would need to be described somehow with another emoji.
